import { ILawyers } from "../model/lawyers-model"

export const initialState: ILawyers = {
    id: 0,
    username: "",
    password: "",
    email: "",
    birth: "",
    name: "",
    phone: "",
    image: "",
    visitCost: "",
    phoneCost: "",
    videoCost: "",
    university: "",
    major: "",
    law: "",
    lawyerNo: "",
    belong: "",
    address: "",
    addressDetail: "",
    belongPhone: "",
    premium: false,
    auth: true,
    account: "",
    startTime: "",
    endTime: "",
}